Revert "gclient eval: Get rid of global_scope, local_scope and functions other than Var."
This reverts commit 9f531298e1a38ccd52b4bd8c47593ccc8f514e04
and fixes the following gclient sync break on Windows:
Traceback (most recent call last):
  File "F:\depot_tools\gclient.py", line 103, in <module>
    import gclient_eval
  File "F:\depot_tools\gclient_eval.py", line 359
    exec(content, global_scope, local_scope)

SyntaxError: unqualified exec is not allowed in function 'Parse' it contains a nested function with free variables
Bug: 2
Change-Id: Ibe5bc0f3c0b4a0e4eba78627ddd2fd2e87b17d7e