Update patch set 3
Patch Set 3:

This seems to be causing some weirdness in our setup where we have a local version of goma installed on machines (don't know if that's the cause):

$ update_depot_tools 
using /run/user/1000/goma_tsniatowski as tmpdir
update f87f26f549d3513bcf3fd811a89444fd1da9cde3@1569480905 -> 6cff373df4908e2fbdc7dced3e5f03d0a4337da8@1570497285
Traceback (most recent call last):
  File "/home/tsniatowski/depot_tools/.cipd_bin/goma_ctl.py", line 2730, in <module>
    sys.exit(main())
  File "/home/tsniatowski/depot_tools/.cipd_bin/goma_ctl.py", line 2725, in main
    goma.Dispatch(sys.argv[1:])
  File "/home/tsniatowski/depot_tools/.cipd_bin/goma_ctl.py", line 1214, in Dispatch
    self._action_mappings.get(args[0], self._DefaultAction)()
  File "/home/tsniatowski/depot_tools/.cipd_bin/goma_ctl.py", line 706, in _UpdateHook
    self._env.RestartCompilerProxy()
AttributeError: 'GomaEnvPosix' object has no attribute 'RestartCompilerProxy'

I haven't looked too closely but it looks like there should be a way to opt out of the goma version in depot_tools.

Patch-set: 3
CC: Gerrit User 1261977 <1261977@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>