Update patch set 3
Patch Set 3:

Looks like this CL breaks "gclient sync". I am seeing the below message when running "gclient sync":

Error: resolving package: failed to resolve package version (line 14): package "infra/tools/luci/led/linux-amd64" doesn't have instance with version "git_revision:8bc0df73831e1528f7d2090bd03abc098261455b".

Patch-set: 3
CC: Gerrit User 1209910 <1209910@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>