Update patch set 4
Patch Set 4:

i'm getting an error that looks like it might have been caused by this change:

% roll-dep src/third_party/cros_system_api
Traceback (most recent call last):
  File "/usr/local/google/home/derat/local/depot_tools/roll_dep.py", line 266, in <module>
    sys.exit(main())
  File "/usr/local/google/home/derat/local/depot_tools/roll_dep.py", line 228, in main
    full_dir, dependency, gclient_dict, args.roll_to)
  File "/usr/local/google/home/derat/local/depot_tools/roll_dep.py", line 130, in calculate_roll
    _, _, head = gclient_dict['deps'][dependency].partition('@')
AttributeError: '_NodeDict' object has no attribute 'partition'

my depot_tools checkout is at 1ad681eca27a4b40dd61ada6da0c8c1bb0c634cc.

Patch-set: 4
CC: Gerrit User 1000042 <1000042@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>