Update patch set 7
Patch Set 7:

This change seems to be causing a python exception when I gclient sync in v8:

```
Traceback (most recent call last):
  File "/home/binji/dev/depot_tools/gclient.py", line 2681, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/binji/dev/depot_tools/gclient.py", line 2667, in main
    return dispatcher.execute(OptionParser(), argv)
  File "/home/binji/dev/depot_tools/subcommand.py", line 252, in execute
    return command(parser, args[1:])
  File "/home/binji/dev/depot_tools/gclient.py", line 2422, in CMDsync
    ret = client.RunOnDeps('update', args)
  File "/home/binji/dev/depot_tools/gclient.py", line 1512, in RunOnDeps
    self.RunHooksRecursively(self._options, pm)
  File "/home/binji/dev/depot_tools/gclient.py", line 1032, in RunHooksRecursively
    progress.update(extra=hook.name)
  File "/home/binji/dev/depot_tools/third_party/repo/progress.py", line 51, in update
    text += ' ' + extra
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

Patch-set: 7
CC: Gerrit User 1002783 <1002783@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>