Update patch set 4
Patch Set 4:

It looks like this is causing some issues on some bots (like the Win x64 PGO one): https://luci-milo.appspot.com/buildbot/chromium.fyi/Chromium%20Win%20x64%20PGO%20Builder/20025 :

IOError: [Errno 2] No such file or directory: 'vs_files\\d3cb0e37bdd120ad0ac4650b674b09e81be45616\\win_sdk\\Extension SDKs\\WindowsMobile\\10.0.10586.0\\Include\\WinRT\\windows.phone.system.userprofile.gameservices.core.h'

Could it be that the path name is now too long?

Patch-set: 4