Update patch set 2
Patch Set 2:

> Patch Set 2:
> 
> > Patch Set 2:
> > 
> > I think this might be hitting me:
> > 
> > C:\src\chromium\src (recolor_toolbar)>python --version
> > Python 2.7.3
> > 
> > C:\src\chromium\src (recolor_toolbar)>gclient sync
> > Traceback (most recent call last):
> >   File "C:\src\depot_tools\gclient.py", line 103, in <module>
> >     import gclient_eval
> >   File "C:\src\depot_tools\gclient_eval.py", line 359
> >     exec(content, global_scope, local_scope)
> > SyntaxError: unqualified exec is not allowed in function 'Parse' it contains a nested function with free variables
> > 
> > Am I wielding it wrong? I've tried both with the system python and depot_tools python.
> 
> With a local revert of this I can sync chromium with: \src\depot_tools\python.bat \src\depot_tools\gclient.py sync
> 
> This hit robliao@ as well.

It was another change [1], though you might already be aware of that. I think it was caused by older versions of Python. It seems to work fine in 2.7.13.
It should be ok now, lots of people were trying to revert it at the same time :P
[1] https://chromium-review.googlesource.com/c/chromium/tools/depot_tools/+/973749

Patch-set: 2