Update patch set 3
Patch Set 3:

> Patch Set 3:
> 
> > Patch Set 3:
> > 
> > after reverting this patch on my local depot_tools I can work again...
> 
> I can confirm a similar issue, and git bisecting the changes in depot_tools I ended up that this patch was the culprit.
> 
> In more detail, this is the error I get:
> 
>     $ git cl upload && git cl try
>     Traceback (most recent call last):
>       File "/home/mario/work/chromium/depot_tools/metrics.py", line 262, in print_notice_and_exit
>         yield
>       File "/home/mario/work/chromium/depot_tools/git_cl.py", line 5538, in <module>
>         sys.exit(main(sys.argv[1:]))
>       File "/home/mario/work/chromium/depot_tools/git_cl.py", line 5520, in main
>         return dispatcher.execute(OptionParser(), argv)
>       File "/home/mario/work/chromium/depot_tools/subcommand.py", line 252, in execute
>         return command(parser, args[1:])
>       File "/home/mario/work/chromium/depot_tools/git_cl.py", line 4545, in CMDupload
>         return cl.CMDUpload(options, args, orig_args)
>       File "/home/mario/work/chromium/depot_tools/git_cl.py", line 1562, in CMDUpload
>         self._codereview_impl.EnsureCanUploadPatchset(force=options.force)
>       File "/home/mario/work/chromium/depot_tools/git_cl.py", line 1982, in EnsureCanUploadPatchset
>         ['DETAILED_ACCOUNTS', 'CURRENT_REVISION', 'CURRENT_COMMIT', 'LABELS'])
>       File "/home/mario/work/chromium/depot_tools/git_cl.py", line 2223, in _GetChangeDetail
>         self._GetGerritHost(), self._GerritChangeIdentifier(), options)
>       File "/home/mario/work/chromium/depot_tools/gerrit_util.py", line 649, in GetChangeDetail
>         return ReadHttpJsonResponse(CreateHttpConn(host, path))
>       File "/home/mario/work/chromium/depot_tools/gerrit_util.py", line 483, in ReadHttpJsonResponse
>         fh = ReadHttpResponse(conn, accept_statuses)
>       File "/home/mario/work/chromium/depot_tools/gerrit_util.py", line 415, in ReadHttpResponse
>         response, contents = conn.request(**conn.req_params)
>       File "/home/mario/work/chromium/depot_tools/third_party/httplib2/__init__.py", line 1609, in request
>         (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
>       File "/home/mario/work/chromium/depot_tools/third_party/httplib2/__init__.py", line 1351, in _request
>         (response, content) = self._conn_request(conn, request_uri, method, body, headers)
>       File "/home/mario/work/chromium/depot_tools/third_party/httplib2/__init__.py", line 1272, in _conn_request
>         conn.connect()
>       File "/home/mario/work/chromium/depot_tools/third_party/httplib2/__init__.py", line 1059, in connect
>         raise SSLHandshakeError(e)
>     SSLHandshakeError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)

ca. 7 days and no revert.

please proceed with fix for original bug, not with reverting one major version with other one (previous). this is potential room for other regressions too.

Patch-set: 3