Update patch set 1
Patch Set 1: Commit-Queue+2

The tests are really harsh, they compare callstack and they include a duration.
Thus it can fail if the test is slower on the bot.

  Traceback (most recent call last):
    File "depot_tools\tests\presubmit_unittest.py", line 3036, in testSurfaceExceptions
      self.assertEqual('5\n5 (0.00s) failed\nstdout', messages[2])
  AssertionError: '5\n5 (0.00s) failed\nstdout' != '5\n5 (0.01s) failed\nstdout'
    5
  - 5 (0.00s) failed
  ?       ^
  + 5 (0.01s) failed
  ?       ^

Sending again to the CQ.

Patch-set: 1
Reviewer: Gerrit User 1116027 <1116027@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Commit-Queue=+2