Update patch set 16
Patch Set 16:

This broke roll-deps for me in PDFium:

$ roll-dep third_party/freetype/src/ --roll-to 9e345c911714ed62250be13d03d72e25d91fbc77
third_party/freetype/src: Rolling from 2157d8fa6f to 9e345c9117
Traceback (most recent call last):
  File "/$HOME/depot_tools/roll_dep.py", line 274, in <module>
    sys.exit(main())
  File "/$HOME/depot_tools/roll_dep.py", line 253, in main
    gclient_eval.SetRevision(gclient_dict, dependency, roll_to)
  File "/$HOME/depot_tools/gclient_eval.py", line 791, in SetRevision
    _UpdateRevision(gclient_dict['deps'], dep_name, new_revision)
  File "/$HOME/depot_tools/gclient_eval.py", line 750, in _UpdateRevision
    dep_node = dep_dict.GetNode(dep_key)
AttributeError: 'dict' object has no attribute 'GetNode'

Patch-set: 16
CC: Gerrit User 1001934 <1001934@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>