Pass an auth_config when creating Changelist in "git map-branches".
The command "git map-branches -vvv" which queries gerrit for the
status of the branch started to fail with the following exception:

    File "/Users/sdefresne/Tools/depot_tools/auth.py", line 184, in extract_auth_config_from_options
      refresh_token_json=options.auth_refresh_token_json)
  AttributeError: 'Options' object has no attribute 'auth_refresh_token_json'

This comes from the fact that no auth_options was passed to the
Changelist() constructor thus defaulting to None. Instead use a
default constructed config from auth module.

BUG=None

Change-Id: I66080f57d786dc8f6e6feb85b69a5e1df76b8b2e