Update patch set 5
Patch Set 5:

> Patch Set 2:
> 
> > Patch Set 2:
> > 
> > When I ran autoninja on a goma directory it hung indefinitely. 
> 
> hmm, reproducible.
> seems subprocess's communicate would cause that it hung indefinitely?
> goma_ctl.py launches compiler_proxy.exe as detached process and finishes, but communicate waits for compiler_proxy.exe's termination?
> 
> without using communicate, it seems to work.
> 

Hmm, interesting.  Since we do not use subprocess.PIPE, we might use the optimized path.
https://github.com/python/cpython/blob/2.7/Lib/subprocess.py#L452

It looks equivalent to just calling wait().

> > I found the python.exe commandline it had run and manually executed it and got this error:
> > 
> > c:\src\chromium3\src>"c:\src\depot_tools\win_tools-2_7_6_bin\python\bin\python.exe"  c:\src\depot_tools\autoninja.py "-C out\debug base"
> > Traceback (most recent call last):
> >   File "C:\src\goma\goma-win64\goma_ctl.py", line 2608, in <module>
> >     sys.exit(main())
> >   File "C:\src\goma\goma-win64\goma_ctl.py", line 2602, in main
> >     goma = GetGomaDriver()
> >   File "C:\src\goma\goma-win64\goma_ctl.py", line 2596, in GetGomaDriver
> >     env = _GOMA_ENVS[os.name]()
> >   File "C:\src\goma\goma-win64\goma_ctl.py", line 2048, in __init__
> >     self._win32process = __import__('win32process')
> > ImportError: DLL load failed: %1 is not a valid Win32 application.
> > Exception AttributeError: "'GomaEnvWin' object has no attribute '_delete_tmp_dir'" in <bound method GomaEnvWin.__del__ of <__main__.GomaEnvWin object at 0x04B56A70>> ignored
> 
> I guess this is because you invoke python.exe instead of python.bat in depot_tools
> python.bat sets up path for these imports.
> 
> > 
> > I ran c:\src\goma\goma-win64\goma_ctl.bat update and it said Goma is already up-to-date. This is on Windows. I guess the code to invoke goma_ctl.py from autoninja.py isn't quite right for Windows.
> > 
> > Question: what's the different between goma_ctl.py start and goma_ctl.py ensure_start?
> 
> start would fail if it is already started.
> ensure_start would start if it is not started yet, or do nothing if it is already started.

Patch-set: 5
Reviewer: Gerrit User 1107806 <1107806@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>