Create patch set 4
Change has been successfully rebased and submitted as 6551a7eb433575243c5212bd2be9ef0930e2dcca

2 is the latest approved patch-set.
The change was submitted with unreviewed changes in the following files:

```
The name of the file: presubmit_diff.py
Insertions: 4, Deletions: 2.

@@ -16,7 +16,8 @@
 import concurrent.futures
 
 import gclient_utils
-from gerrit_util import CreateHttpConn, ReadHttpResponse
+from gerrit_util import (CreateHttpConn, ReadHttpResponse,
+                         MAX_CONCURRENT_CONNECTION)
 import subprocess2
 
 DEV_NULL = "/dev/null"
@@ -130,7 +131,8 @@
         RuntimeError: If a file is missing in both the root and the repo.
     """
     diffs = {}
-    with concurrent.futures.ThreadPoolExecutor() as executor:
+    with concurrent.futures.ThreadPoolExecutor(
+            max_workers=MAX_CONCURRENT_CONNECTION) as executor:
         futures_to_file = {
             executor.submit(_create_diff, host, repo, ref, root, file): file
             for file in files
```


Patch-set: 4
Patch-set-description: Rebase
Subject: Fetch file contents from Gitiles in parallel
Status: merged
Commit: 6551a7eb433575243c5212bd2be9ef0930e2dcca
Tag: autogenerated:gerrit:merged
Groups: 0c70885537c436b7490623785210e34fc15e9a30
Label: Code-Review=+1, 95dec59ab7dce58c3bdda21b678cf67eceac19ff Gerrit User 1560543 <1560543@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Commit-Queue=+2, c4ac8b8c952cf493007e868c455a6fa6938f0a89 Gerrit User 1367998 <1367998@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: SUBM=+1, d8f1ec1779549a36a5fc51de591a5b0371965344
Submission-id: 5384647
Submitted-with: OK
Submitted-with: Rule-Name: gerrit~DefaultSubmitRule
Submitted-with: MAY: Auto-Submit
Submitted-with: MAY: Code-Coverage
Submitted-with: MAY: Code-Review: Gerrit User 1560543 <1560543@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Submitted-with: MAY: Commit-Queue: Gerrit User 1367998 <1367998@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Submitted-with: MAY: Feels
Submitted-with: MAY: Bot-Commit
Submitted-with: MAY: Owners-Override
Submitted-with: OK
Submitted-with: Rule-Name: Code-Owners