Update patch set 4
Patch Set 4:

This CL may be causing issues with the Skia windows GCE bots.  We are now seeing 
File "c:\b\s\swarming_bot.1.zip\config\bot_config.py", line 32, in <module>
  ImportError: No module named win32con

Patch-set: 4
CC: Gerrit User 1185234 <1185234@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>