setup_color: Don't fill created string buffer with nulls
This causes an error since Python 3.5 due to a regression (https://bugs.python.org/issue32745):
Traceback (most recent call last):
  File "C:\Google\depot_tools\metrics.py", line 267, in print_notice_and_exit
    yield
  File "C:\Google\depot_tools\gclient.py", line 3153, in <module>
    sys.exit(main(sys.argv[1:]))
  File "C:\Google\depot_tools\gclient.py", line 3136, in main
    setup_color.init()
  File "C:\Google\depot_tools\setup_color.py", line 70, in init
    buf = ctypes.create_string_buffer('\0', 1024)
  File "C:\Program Files\Python38\lib\ctypes\__init__.py", line 63, in create_string_buffer
    raise TypeError(init)
TypeError: <Unicode console <stderr>>.write: ArgumentError("argument 2: <class 'ValueError'>: embedded null character")

Simply not filling the buffer with NULLs doesn't change the behaviour.

Bug: 942522
Change-Id: I1feb81555e995597b0b70f4aee9151fea755510c