Update patch set 3
Patch Set 3:

This seems to be causing a crash on windows:
Traceback (most recent call last):
  File "C:\src\depot_tools\metrics.py", line 267, in print_notice_and_exit
    yield
  File "C:\src\depot_tools\git_cl.py", line 5446, in <module>
    sys.exit(main(sys.argv[1:]))
  File "C:\src\depot_tools\git_cl.py", line 5428, in main
    return dispatcher.execute(OptionParser(), argv)
  File "C:\src\depot_tools\subcommand.py", line 252, in execute
    return command(parser, args[1:])
  File "C:\src\depot_tools\metrics.py", line 252, in _inner
    return self._collect_metrics(func, command_name, *args, **kwargs)
  File "C:\src\depot_tools\metrics.py", line 232, in _collect_metrics
    gclient_utils.reraise(exception[0], exception[1], exception[2])
  File "C:\src\depot_tools\metrics.py", line 205, in _collect_metrics
    result = func(*args, **kwargs)
  File "C:\src\depot_tools\git_cl.py", line 4401, in CMDupload
    ret = cl.CMDUpload(options, args, orig_args)
  File "C:\src\depot_tools\git_cl.py", line 1528, in CMDUpload
    ret = self.CMDUploadChange(options, git_diff_args, custom_cl_base, change)
  File "C:\src\depot_tools\git_cl.py", line 2391, in CMDUploadChange
    options.force, change_desc)
  File "C:\src\depot_tools\git_cl.py", line 2615, in _ComputeParent
    change_desc)
  File "C:\src\depot_tools\git_cl.py", line 139, in DieWithError
    '='*72 + '\n')
TypeError: cannot concatenate 'str' and 'ChangeDescription' objects

Patch-set: 3
CC: Gerrit User 1000763 <1000763@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>