Update patch set 9
Patch Set 9:

This is missing "import sys" in several code paths.

Traceback (most recent call last):
  File "/usr/local/google/home/spang/depot_tools/gn.py", line 73, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/google/home/spang/depot_tools/gn.py", line 51, in main
    'gn', 'gn' + gclient_paths.GetExeSuffix())
  File "/usr/local/google/home/spang/depot_tools/gclient_paths.py", line 122, in GetExeSuffix
    if sys.platform.startswith(('cygwin', 'win')):
NameError: global name 'sys' is not defined

Patch-set: 9
CC: Gerrit User 1001794 <1001794@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>