Update patch set 3
Patch Set 3:

This change breaks my_activity.py since xrange doesn't exist in Python 3:

timvp@timvp:~/code/chromium/src/third_party/angle$ my_activity.py
WARNING:root:Consider installing python-keyring
Loading dataTraceback (most recent call last):
  File "/usr/local/google/home/timvp/code/depot_tools/my_activity.py", line 966, in <module>
    sys.exit(main())
  File "/usr/local/google/home/timvp/code/depot_tools/my_activity.py", line 917, in main
    my_activity.get_changes()
  File "/usr/local/google/home/timvp/code/depot_tools/my_activity.py", line 537, in get_changes
    gerrit_changes = itertools.chain.from_iterable(gerrit_changes.get())
  File "/usr/local/google/home/timvp/code/depot_tools/bootstrap-3.8.0.chromium.8_bin/python3/lib/python3.8/multiprocessing/pool.py", line 768, in get
    raise self._value
  File "/usr/local/google/home/timvp/code/depot_tools/bootstrap-3.8.0.chromium.8_bin/python3/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/google/home/timvp/code/depot_tools/bootstrap-3.8.0.chromium.8_bin/python3/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/usr/local/google/home/timvp/code/depot_tools/my_activity.py", line 535, in <lambda>
    lambda instance: self.gerrit_search(instance, owner=self.user),
  File "/usr/local/google/home/timvp/code/depot_tools/my_activity.py", line 238, in gerrit_search
    issues = self.gerrit_changes_over_rest(instance, filters)
  File "/usr/local/google/home/timvp/code/depot_tools/my_activity.py", line 214, in gerrit_changes_over_rest
    return list(gerrit_util.GenerateAllChanges(instance['url'], req,
  File "/usr/local/google/home/timvp/code/depot_tools/gerrit_util.py", line 552, in GenerateAllChanges
    page = QueryChanges(host, params, first_param, limit, o_params,
  File "/usr/local/google/home/timvp/code/depot_tools/gerrit_util.py", line 507, in QueryChanges
    return ReadHttpJsonResponse(CreateHttpConn(host, path))
  File "/usr/local/google/home/timvp/code/depot_tools/gerrit_util.py", line 359, in CreateHttpConn
    a = Authenticator.get().get_auth_header(bare_host)
  File "/usr/local/google/home/timvp/code/depot_tools/gerrit_util.py", line 98, in get
    if GceAuthenticator.is_gce():
  File "/usr/local/google/home/timvp/code/depot_tools/gerrit_util.py", line 283, in is_gce
    cls._cache_is_gce = cls._test_is_gce()
  File "/usr/local/google/home/timvp/code/depot_tools/gerrit_util.py", line 290, in _test_is_gce
    resp, _ = cls._get(cls._INFO_URL)
  File "/usr/local/google/home/timvp/code/depot_tools/gerrit_util.py", line 299, in _get
    for i in xrange(TRY_LIMIT):
NameError: name 'xrange' is not defined

Patch-set: 3
CC: Gerrit User 1297197 <1297197@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>