Update patch set 2
Patch Set 2: Code-Review+1 Commit-Queue+2

The error was:

Traceback (most recent call last):
  File "/usr/local/google/home/droger/lib/depot_tools/gclient.py", line 2418, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/google/home/droger/lib/depot_tools/gclient.py", line 2404, in main
    return dispatcher.execute(OptionParser(), argv)
  File "/usr/local/google/home/droger/lib/depot_tools/subcommand.py", line 252, in execute
    return command(parser, args[1:])
  File "/usr/local/google/home/droger/lib/depot_tools/gclient.py", line 2153, in CMDsync
    ret = client.RunOnDeps('update', args)
  File "/usr/local/google/home/droger/lib/depot_tools/gclient.py", line 1445, in RunOnDeps
    work_queue.flush(revision_overrides, command, args, options=self._options)
  File "/usr/local/google/home/droger/lib/depot_tools/gclient_utils.py", line 1049, in run
    self.item.run(*self.args, **self.kwargs)
  File "/usr/local/google/home/droger/lib/depot_tools/gclient.py", line 852, in run
    self.ParseDepsFile()
  File "/usr/local/google/home/droger/lib/depot_tools/gclient.py", line 745, in ParseDepsFile
    self._postprocess_deps(orig_deps, rel_prefix), use_relative_paths)
  File "/usr/local/google/home/droger/lib/depot_tools/gclient.py", line 568, in _postprocess_deps
    deps[d] = self.custom_deps[d]
TypeError: 'FrozenDict' object does not support item assignment

Patch-set: 2
Reviewer: Gerrit User 1003232 <1003232@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Reviewer: Gerrit User 1002740 <1002740@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Code-Review=+1
Label: Commit-Queue=+2