Make update_depot_tools return exit code properly on all platforms.
Before on Windows:
C:\depot_tools>update_depot_tools
Updating depot_tools...
error: Your local changes to the following files would be overwritten by checkout:
        presubmit_canned_checks.py
Please commit your changes or stash them before you switch branches.
Aborting
Failed to update depot_tools.

C:\depot_tools>echo %errorlevel%
0

After:
<...>
C:\depot_tools>echo %errorlevel%
1

Before on Linux:
user@WDPC:~/depot_tools$ ./update_depot_tools
Updating depot_tools...
depot_tools update failed. Conflict in .
error: Your local changes to the following files would be overwritten by checkout:
        presubmit_canned_checks.py
Please commit your changes or stash them before you switch branches.
Aborting
user@WDPC:~/depot_tools$ echo $?
0

After:
<...>
user@WDPC:~/depot_tools$ echo $?
1
Change-Id: I64459982bcd9cc3db1319a9b39224b7a7af8c5aa