Fix missing unicode check in gclient
The error:
Error: dependency url must be either string or None, instead of unicode

Bug: 942522
Change-Id: I73e0a04679b2f402dfc46a26f58f1392320a8bfc