Update patch set 6
Patch Set 6:

I think this CL caused the ANGLE CQ to explode (again)

https://ci.chromium.org/p/angle/builders/try/presubmit/2974

Traceback (most recent call last):
  File "/b/s/w/ir/kitchen-checkout/depot_tools/gclient.py", line 97, in <module>
    import six
ImportError: No module named six

Patch-set: 6
CC: Gerrit User 1329751 <1329751@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>