Revert "Remove use_relative_hooks now that all deprecated uses are removed."
This reverts commit 4de6cfa5a9368a4a10937e6527e55bc993113858.

Reason for revert:
Error: 417> Wrong keys 'use_relative_hooks'
in chromeos/assistant/libassistant

Full error output is:
https://paste.googleplex.com/6176019356581888

Original change's description:
> Remove use_relative_hooks now that all deprecated uses are removed.
> 
> Bug: chromium:1107325
> Change-Id: Iac1ff8ef9426c8f57b6e12783de0ffbb0625ef2b
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/tools/depot_tools/+/2349170
> Reviewed-by: Josip Sokcevic <sokcevic@google.com>
> Commit-Queue: Corentin Wallez <cwallez@chromium.org>

TBR=cwallez@chromium.org,ehmaldonado@chromium.org,infra-scoped@luci-project-accounts.iam.gserviceaccount.com,sokcevic@google.com

Change-Id: Ic15017f815810303cd29f453cec0a178451bf55a
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: chromium:1107325