Update patch set 5
Patch Set 5:

I ended up readding the newline, so the output now looks like this:

$ gclient sync -j20 -D -f
Syncing projects: 100% (162/162), done.                                                                
Running hooks:  49% (32/65) webui_node_modules     
________ running '/usr/bin/python src/tools/perf/conditionally_execute --gyp-condition fetch_telemetry_dependencies=1 src/third_party/catapult/telemetry/bin/fetch_telemetry_binary_dependencies' in '/usr/local/google/home/dcheng/src/chrome'                  
Not found "fetch_telemetry_dependencies=1" condition in GYP_DEFINES="[]". Skip script execution.       
Running hooks: 100% (65/65), done.
$

Without the newline, it overwrites the partial progress messages from Running hooks. This also seems more consistent with how syncing reports errors:

$ # -j1 because this often says 100% otherwise, even on errors
$ gclient sync --nohooks -j1
Syncing projects:  59% (96/162)                    
src/v8 (ERROR)           
----------------------------------------           
[0:00:38] Started.       
----------------------------------------           
Error:                   
____ src/v8 at 69858b2e444f493157642d01b055e10801ebd01e                                                
        You have unstaged changes.                 
        Please commit, stash, or reset.            

$

Patch-set: 5
Reviewer: Gerrit User 1001168 <1001168@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>