Don't escape "commit" value for Gerrit branch/tag creation.
This value is passed in the JSON body, not in the URL, so does not need
to be escaped, otherwise trying to make a branch/tag from another
branch/tag leads to errors like:

  gerrit_util.GerritError: (400) Bad Request: invalid revision "refs%2Fheads%2Fchromium%2F4665"

BUG=1052179
R=linxinan@chromium.org, sokcevic@google.com

Change-Id: I80d709370165fcb84a3375e18b67d4a921be9a8d