git_cache: Call decode() on gsutil output in Mirror.bootstrap_repo()
This makes the code work with Python 3. Not doing that makes `gclient sync'
fail when a new repository needs to be bootstrapped and added to the cache:

Traceback (most recent call last):
  File "/data/src/depot_tools/metrics.py", line 267, in print_notice_and_exit
    yield
  File "/data/src/depot_tools/gclient.py", line 3158, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/data/src/depot_tools/gclient.py", line 3144, in main
    return dispatcher.execute(OptionParser(), argv)
  File "/data/src/depot_tools/subcommand.py", line 252, in execute
    return command(parser, args[1:])
  File "/data/src/depot_tools/gclient.py", line 2701, in CMDsync
    ret = client.RunOnDeps('update', args)
  File "/data/src/depot_tools/gclient.py", line 1738, in RunOnDeps
    work_queue.flush(revision_overrides, command, args, options=self._options,
  File "/data/src/depot_tools/gclient_utils.py", line 914, in flush
    reraise(e[0], e[1], e[2])
  File "/data/src/depot_tools/gclient_utils.py", line 72, in reraise
    raise value
  File "/data/src/depot_tools/gclient_utils.py", line 991, in run
    self.item.run(*self.args, **self.kwargs)
  File "/data/src/depot_tools/gclient.py", line 915, in run
    self._got_revision = self._used_scm.RunCommand(command, options, args,
  File "/data/src/depot_tools/gclient_scm.py", line 132, in RunCommand
    return getattr(self, command)(options, args, file_list)
  File "/data/src/depot_tools/gclient_scm.py", line 545, in update
    self._UpdateMirrorIfNotContains(mirror, options, rev_type, revision)
  File "/data/src/depot_tools/gclient_scm.py", line 984, in _UpdateMirrorIfNotContains
    mirror.populate(verbose=options.verbose,
  File "/data/src/depot_tools/git_cache.py", line 601, in populate
    self._ensure_bootstrapped(depth, bootstrap)
  File "/data/src/depot_tools/git_cache.py", line 523, in _ensure_bootstrapped
    self.bootstrap_repo(self.mirror_path))
  File "/data/src/depot_tools/git_cache.py", line 417, in bootstrap_repo
    latest_dir = self._GetMostRecentCacheDirectory(ls_out_set)
  File "/data/src/depot_tools/git_cache.py", line 322, in _GetMostRecentCacheDirectory
    m = ready_file_pattern.match(name)
TypeError: cannot use a string pattern on a bytes-like object

Bug: 984182
Change-Id: I195b612839e2b38c329606a49e6f97084bf7cac2