[depot_tools] Update gsutil.py to rmtree bin_dir
https://logs.chromium.org/logs/infra/buildbucket/cr-buildbucket/8749300159860839489/+/u/bot_update/stdout
```
  File "/b/s/w/ir/kitchen-checkout/depot_tools/gsutil.py", line 321, in main
    return run_gsutil(args.target, args.args, clean=args.clean)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/b/s/w/ir/kitchen-checkout/depot_tools/gsutil.py", line 229, in run_gsutil
    gsutil_bin = ensure_gsutil(VERSION, target, clean)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/b/s/w/ir/kitchen-checkout/depot_tools/gsutil.py", line 133, in ensure_gsutil
    shutil.move(download_dir, bin_dir)
  File "/home/chrome-bot/.cache/.vpython-root/store/cpython+qocd3gso2qlupcvi74a8cf00v0/contents/lib/python3.11/shutil.py", line 851, in move
    raise Error("Destination path '%s' already exists" % real_dst)
shutil.Error: Destination path '/b/s/w/ir/kitchen-checkout/depot_tools/external_bin/gsutil/gsutil_4.68/d' already exists
```

Seems like the rename of bin_dir to the clean_dir fails and then the
bin_dir is never cleared before a newly downloaded gsutil tries to move
in.

Bug: b/328065301
Change-Id: I6976377c991f007160ea1a770947a03ce8857f00