Revert "gclient eval: Expand vars while parsing DEPS files"
This reverts commit
88f9c40e0ccefb491790888a703c857b0c3ec6d1
and is required to revert
9f531298e1a38ccd52b4bd8c47593ccc8f514e04.

9f531298e1a38ccd52b4bd8c47593ccc8f514e04
causes the following gclient sync break on Windows
Traceback (most recent call last):
  File "F:\depot_tools\gclient.py", line 103, in <module>
    import gclient_eval
  File "F:\depot_tools\gclient_eval.py", line 359
    exec(content, global_scope, local_scope)
SyntaxError: unqualified exec is not allowed in function 'Parse' it contains a nested function with free variables


Bug: 821199
Change-Id: Iaba45d579570482c52821148ae583b3756388508