Update patch set 4
Patch Set 4:

I think something is still missing here. I'm seeing the error:

  File "/mnt/data/b/depot_tools/git_cl.py", line 5155, in CMDland
    options.verbose, options.parallel)
AttributeError: Values instance has no attribute 'parallel'

Maybe missing a parser.add_option('--parallel') somewhere?

Patch-set: 4
CC: Gerrit User 1002222 <1002222@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>