Reland "siso.py: check ninja marker"
This reverts commit b1c6497e19ef0efe51a24e28bfcc18189d1b65f1.

Reason for revert: WIP

Original change's description:
> Revert "siso.py: check ninja marker"
>
> This reverts commit 41bbfb8b90d7290acb7ef406dfbea01724fe83e3.
>
> Reason for revert: 
> ukai@ukai ...src/chromium/src % siso ninja -C out/siso
> depot_tools/siso.py: Using Siso binary from SISO_PATH: /usr/local/google/home/ukai/go/bin/siso.
> Traceback (most recent call last):
>   File "/usr/local/google/home/ukai/depot_tools/siso.py", line 115, in <module>
>     sys.exit(main(sys.argv))
>              ^^^^^^^^^^^^^^
>   File "/usr/local/google/home/ukai/depot_tools/siso.py", line 104, in main
>     checkOutdir(args[1:])
>   File "/usr/local/google/home/ukai/depot_tools/siso.py", line 21, in checkOutdir   
>     for i, arg in enumerate(ninja_args):
>                             ^^^^^^^^^^
> NameError: name 'ninja_args' is not defined. Did you mean: 'ninja_marker'?
>
>
> Original change's description:
> > siso.py: check ninja marker
> >
> > If out dir was built by Ninja, don't build by Siso.
> >
> > (still allow `siso query` etc)
> >
> > Bug: b/338414465
> > Change-Id: I48f8fbb5e83714fd3d27ff3a2bfffe929e4ef121
> > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/tools/depot_tools/+/5518396
> > Reviewed-by: Junji Watanabe <jwata@google.com>
> > Commit-Queue: Junji Watanabe <jwata@google.com>
> > Auto-Submit: Fumitoshi Ukai <ukai@google.com>
> > Commit-Queue: Fumitoshi Ukai <ukai@google.com>
>
> Bug: b/338414465
> Change-Id: Ie69ca1b6c1d3dc47475d9356beab29a917356479
> No-Presubmit: true
> No-Tree-Checks: true
> No-Try: true
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/tools/depot_tools/+/5514902
> Reviewed-by: Philipp Wollermann <philwo@chromium.org>
> Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
> Commit-Queue: Fumitoshi Ukai <ukai@google.com>

Bug: b/338414465
Change-Id: Idb18ad9191a062f83b538c1e2a76ee77200c4df0